# Generated by Django 2.0.6 on 2019-02-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnow', '0002_auto_20190221_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_first_name', models.CharField(max_length=30)),
                ('child_last_name', models.CharField(max_length=10)),
                ('child_mom', models.CharField(max_length=10)),
            ],
        ),
    ]
